Feature update with bim
w3c-lbd-cg/wot-usecases pull request #7
Opened 2021-02-21 07:55 UTC by GeorgFerdinandSchneider

Added references to BIM and Protocol bindings as discussed with @HervePruvost  and @chung-edison 

Minor revision of text and ordering

Final PR before submitting to via a PR https://github.com/w3c/wot-usecases

2021-02-22 11:44 UTC, chung-edison requested changes
`"brick": "https://brickschema.org/schema/1.1/Brick#",` should be added to `@context`.

2021-02-22 11:44 UTC, chung-edison commented on USE-CASES/W3C-LBD-CG.md
> +[Edison Chung (MINES St. Etienne)](https://github.com/chung-edison)
https://orcid.org/0000-0002-5672-5508

2021-02-22 11:44 UTC, chung-edison commented on USE-CASES/W3C-LBD-CG.md
>              "sosa": "http://www.w3.org/ns/sosa/",
should add `"brick": "https://brickschema.org/schema/1.1/Brick#",` to `@context`

2021-02-22 11:44 UTC, chung-edison commented on USE-CASES/W3C-LBD-CG.md
> +    "@type": ["sosa:Actuator", "brick:Zone_Air_Temperature_Setpoint", "bot:element"],
should add `"brick": "https://brickschema.org/schema/1.1/Brick#"` to `@context` and remove `"dog"`

2021-02-22 11:50 UTC, chung-edison approved these changes

2021-02-22 17:29 UTC, gtfierro commented
Brick is moving to a namespace without a version number, to simplify further development. The new Brick namespace, as of the [v1.2.0 release](https://github.com/BrickSchema/Brick/releases/tag/v1.2.0) is `https://brickschema.org/schema/Brick#`. We will be updating the website so that this URI redirects to the Turtle serialization of the file soon

2021-02-23 10:36 UTC, GeorgFerdinandSchneider commented
Dear @gtfierro!

Thanks for pointing to the latest release of BRICK and the comment. We are happy to change the IRI of BRICK to the new one as soon as the redirects are in place.

Best

2021-02-24 15:43 UTC, merged

2021-02-24 20:52 UTC, gtfierro commented
The redirect of [https://brickschema.org/schema/Brick#](https://brickschema.org/schema/Brick#) is now in place!